/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AIChiefOfStaffPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var AIChiefOfStaffSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "AI Chief of Staff Settings" });
    this.displayApiKeysSection(containerEl);
    this.displayOllamaSettings(containerEl);
    this.displayGoogleAuthSection(containerEl);
    this.displayPathSettings(containerEl);
    this.displaySchedulingSettings(containerEl);
    this.displayFeatureToggles(containerEl);
    this.displayAdvancedLLMConfig(containerEl);
    this.displayEmailCalendarRules(containerEl);
    this.displayBackgroundServiceConfig(containerEl);
  }
  displayApiKeysSection(containerEl) {
    containerEl.createEl("h2", { text: "\u{1F511} API Keys Configuration" });
    const infoEl = containerEl.createEl("div", { cls: "setting-item-description" });
    infoEl.style.marginBottom = "15px";
    infoEl.style.padding = "10px";
    infoEl.style.backgroundColor = "var(--background-secondary)";
    infoEl.style.borderRadius = "5px";
    infoEl.innerHTML = `
      <strong>Setup Instructions:</strong><br>
      1. Create a Google Cloud project at <a href="https://console.cloud.google.com">console.cloud.google.com</a><br>
      2. Enable Gmail API and Google Calendar API<br>
      3. Create OAuth 2.0 credentials (Desktop App type)<br>
      4. Copy your Client ID and Client Secret below<br>
      <br>
      <em>Your keys are stored locally in your vault's plugin data folder.</em>
    `;
    new import_obsidian.Setting(containerEl).setName("Google OAuth Client ID").setDesc("Your OAuth 2.0 Client ID from Google Cloud Console").addText((text) => {
      text.setPlaceholder("xxxxxxxxxx.apps.googleusercontent.com").setValue(this.plugin.settings.googleClientId).onChange(async (value) => {
        this.plugin.settings.googleClientId = value.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.style.width = "100%";
      text.inputEl.style.minWidth = "300px";
    });
    new import_obsidian.Setting(containerEl).setName("Google OAuth Client Secret").setDesc("Your OAuth 2.0 Client Secret from Google Cloud Console").addText((text) => {
      text.setPlaceholder("Enter your client secret").setValue(this.plugin.settings.googleClientSecret).onChange(async (value) => {
        this.plugin.settings.googleClientSecret = value.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
      text.inputEl.style.width = "100%";
      text.inputEl.style.minWidth = "300px";
    }).addButton((button) => button.setButtonText("Show").onClick(() => {
      var _a;
      const input = (_a = button.buttonEl.parentElement) == null ? void 0 : _a.querySelector("input");
      if (input) {
        if (input.type === "password") {
          input.type = "text";
          button.setButtonText("Hide");
        } else {
          input.type = "password";
          button.setButtonText("Show");
        }
      }
    }));
    const hasCredentials = this.plugin.settings.googleClientId && this.plugin.settings.googleClientSecret;
    const statusEl = containerEl.createEl("div", { cls: "setting-item-description" });
    statusEl.style.marginBottom = "20px";
    statusEl.style.padding = "8px 12px";
    statusEl.style.borderRadius = "4px";
    if (hasCredentials) {
      statusEl.style.backgroundColor = "var(--background-modifier-success)";
      statusEl.style.color = "var(--text-success)";
      statusEl.textContent = "\u2713 API keys configured. Proceed to Google Authentication below.";
    } else {
      statusEl.style.backgroundColor = "var(--background-modifier-error)";
      statusEl.style.color = "var(--text-error)";
      statusEl.textContent = "\u2717 Please enter your Google API keys above to enable Calendar and Gmail features.";
    }
  }
  displayOllamaSettings(containerEl) {
    containerEl.createEl("h2", { text: "\u{1F9E0} Ollama Configuration" });
    new import_obsidian.Setting(containerEl).setName("Ollama URL").setDesc("URL where Ollama is running (default: http://localhost:11434)").addText((text) => text.setPlaceholder("http://localhost:11434").setValue(this.plugin.settings.ollamaUrl).onChange(async (value) => {
      this.plugin.settings.ollamaUrl = value;
      await this.plugin.saveSettings();
      this.plugin.updateServices();
    }));
    const recommendedModels = [
      { value: "gemma3:4b-it-qat", name: "Gemma 3n 4B (Fast, Efficient)" },
      { value: "gemma2:9b", name: "Gemma 2 9B (Balanced)" },
      { value: "llama3:8b", name: "Llama 3 8B (General Purpose)" },
      { value: "mistral:7b", name: "Mistral 7B (Fast)" },
      { value: "custom", name: "Custom Model..." }
    ];
    new import_obsidian.Setting(containerEl).setName("Model Selection").setDesc("Choose an Ollama model for AI processing").addDropdown((dropdown) => {
      recommendedModels.forEach((model) => {
        dropdown.addOption(model.value, model.name);
      });
      const currentModel = this.plugin.settings.ollamaModel;
      const isRecommended = recommendedModels.some((m) => m.value === currentModel);
      dropdown.setValue(isRecommended ? currentModel : "custom");
      dropdown.onChange(async (value) => {
        if (value !== "custom") {
          this.plugin.settings.ollamaModel = value;
          await this.plugin.saveSettings();
          this.plugin.updateServices();
          this.display();
        } else {
          this.display();
        }
      });
    });
    const isCustomModel = !recommendedModels.some((m) => m.value === this.plugin.settings.ollamaModel && m.value !== "custom");
    if (isCustomModel || this.plugin.settings.ollamaModel === "") {
      new import_obsidian.Setting(containerEl).setName("Custom Model Name").setDesc("Enter a custom Ollama model name").addText((text) => text.setPlaceholder("model:tag").setValue(this.plugin.settings.ollamaModel).onChange(async (value) => {
        this.plugin.settings.ollamaModel = value;
        await this.plugin.saveSettings();
        this.plugin.updateServices();
      }));
    }
    const modelInfoEl = containerEl.createEl("div", { cls: "setting-item-description" });
    modelInfoEl.style.marginBottom = "15px";
    modelInfoEl.style.padding = "10px";
    modelInfoEl.style.backgroundColor = "var(--background-secondary)";
    modelInfoEl.style.borderRadius = "5px";
    modelInfoEl.innerHTML = `
      <strong>Model Recommendations:</strong><br>
      \u2022 <strong>Gemma 3n 4B</strong> - Latest efficient model, great for most tasks<br>
      \u2022 <strong>Gemma 2 9B</strong> - More capable, requires more RAM<br>
      \u2022 Run <code>ollama pull gemma3:4b-it-qat</code> to install Gemma 3n
    `;
    new import_obsidian.Setting(containerEl).setName("Test Ollama Connection").setDesc("Verify that Ollama is running and accessible").addButton((button) => button.setButtonText("Test Connection").onClick(async () => {
      button.setButtonText("Testing...");
      const success = await this.plugin.ollamaService.testConnection();
      if (success) {
        new import_obsidian.Notice("\u2705 Ollama connection successful!");
        const models = await this.plugin.ollamaService.listModels();
        if (models.length > 0) {
          new import_obsidian.Notice(`Available models: ${models.join(", ")}`);
        }
      } else {
        new import_obsidian.Notice("\u274C Failed to connect to Ollama. Is it running?");
      }
      button.setButtonText("Test Connection");
    }));
  }
  displayGoogleAuthSection(containerEl) {
    containerEl.createEl("h2", { text: "\u{1F517} Google Authentication" });
    const isAuthenticated = this.plugin.googleAuthService.isAuthenticated();
    const hasCredentials = this.plugin.settings.googleClientId && this.plugin.settings.googleClientSecret;
    if (!hasCredentials) {
      const warningEl = containerEl.createEl("div", { cls: "setting-item-description" });
      warningEl.style.padding = "10px";
      warningEl.style.backgroundColor = "var(--background-modifier-error)";
      warningEl.style.borderRadius = "5px";
      warningEl.style.marginBottom = "15px";
      warningEl.textContent = "Please configure your API keys in the section above first.";
      return;
    }
    if (isAuthenticated) {
      const successEl = containerEl.createEl("div", { cls: "setting-item-description" });
      successEl.style.padding = "10px";
      successEl.style.backgroundColor = "var(--background-modifier-success)";
      successEl.style.borderRadius = "5px";
      successEl.style.marginBottom = "15px";
      successEl.innerHTML = "\u2705 <strong>Connected to Google</strong> - Calendar and Gmail features are active.";
      new import_obsidian.Setting(containerEl).setName("Disconnect Google Account").setDesc("Remove the connection to your Google account").addButton((button) => button.setButtonText("Disconnect").setWarning().onClick(async () => {
        await this.plugin.googleAuthService.logout();
        new import_obsidian.Notice("Disconnected from Google");
        this.display();
      }));
    } else {
      new import_obsidian.Setting(containerEl).setName("Step 1: Authorize with Google").setDesc("Click to open Google authorization page in your browser").addButton((button) => button.setButtonText("Open Google Authorization").setCta().onClick(() => {
        try {
          const authUrl = this.plugin.googleAuthService.generateAuthUrl();
          window.open(authUrl);
          new import_obsidian.Notice("Authorize in your browser, then copy the code and paste it below");
        } catch (error) {
          new import_obsidian.Notice("Please configure Client ID and Secret first");
        }
      }));
      new import_obsidian.Setting(containerEl).setName("Step 2: Enter Authorization Code").setDesc("After authorizing, Google will display a code. Paste it here.").addText((text) => {
        text.setPlaceholder("Paste your authorization code here");
        text.inputEl.style.width = "100%";
        text.inputEl.style.minWidth = "250px";
      }).addButton((button) => button.setButtonText("Connect").setCta().onClick(async () => {
        var _a;
        const input = containerEl.querySelector('input[placeholder="Paste your authorization code here"]');
        const code = (_a = input == null ? void 0 : input.value) == null ? void 0 : _a.trim();
        if (!code) {
          new import_obsidian.Notice("Please enter the authorization code");
          return;
        }
        try {
          button.setButtonText("Connecting...");
          button.setDisabled(true);
          await this.plugin.googleAuthService.exchangeCodeForTokens(code);
          new import_obsidian.Notice("\u2705 Successfully connected to Google!");
          this.display();
        } catch (error) {
          new import_obsidian.Notice(`Failed to authenticate: ${error}`);
          button.setButtonText("Connect");
          button.setDisabled(false);
        }
      }));
    }
  }
  displayPathSettings(containerEl) {
    containerEl.createEl("h2", { text: "\u{1F4C1} Note Paths" });
    const infoEl = containerEl.createEl("div", { cls: "setting-item-description" });
    infoEl.style.marginBottom = "15px";
    infoEl.style.padding = "10px";
    infoEl.style.backgroundColor = "var(--background-secondary)";
    infoEl.style.borderRadius = "5px";
    infoEl.innerHTML = `Configure where the plugin saves meeting debriefs, daily briefings, inbox triage, and time audits. Make sure these paths exist in your vault.`;
    new import_obsidian.Setting(containerEl).setName("Meeting Note Debriefs Folder").setDesc("Folder for meeting debriefs and daily briefings (e.g., Daily Notes)").addText((text) => text.setPlaceholder("Daily Notes").setValue(this.plugin.settings.dailyNotePath).onChange(async (value) => {
      this.plugin.settings.dailyNotePath = value;
      await this.plugin.saveSettings();
      this.plugin.updateFeatures();
    }));
    if (!this.plugin.settings.dailyNotePath) {
      const warningEl = containerEl.createEl("div", { cls: "setting-item-description" });
      warningEl.style.padding = "8px 12px";
      warningEl.style.backgroundColor = "var(--background-modifier-error)";
      warningEl.style.color = "var(--text-error)";
      warningEl.style.borderRadius = "4px";
      warningEl.style.marginBottom = "15px";
      warningEl.textContent = "\u26A0 Please specify a folder for meeting debriefs";
    }
    new import_obsidian.Setting(containerEl).setName("Inbox Triage Note").setDesc("Path to the inbox triage dashboard note (e.g., Inbox Triage.md)").addText((text) => text.setPlaceholder("Inbox Triage.md").setValue(this.plugin.settings.inboxNotePath).onChange(async (value) => {
      this.plugin.settings.inboxNotePath = value;
      await this.plugin.saveSettings();
      this.plugin.updateFeatures();
    }));
    if (!this.plugin.settings.inboxNotePath) {
      const warningEl = containerEl.createEl("div", { cls: "setting-item-description" });
      warningEl.style.padding = "8px 12px";
      warningEl.style.backgroundColor = "var(--background-modifier-error)";
      warningEl.style.color = "var(--text-error)";
      warningEl.style.borderRadius = "4px";
      warningEl.style.marginBottom = "15px";
      warningEl.textContent = "\u26A0 Please specify a path for inbox triage";
    }
    new import_obsidian.Setting(containerEl).setName("Weekly Review Note").setDesc("Path to the weekly time audit note (e.g., Weekly Review.md)").addText((text) => text.setPlaceholder("Weekly Review.md").setValue(this.plugin.settings.weeklyReviewPath).onChange(async (value) => {
      this.plugin.settings.weeklyReviewPath = value;
      await this.plugin.saveSettings();
      this.plugin.updateFeatures();
    }));
    if (!this.plugin.settings.weeklyReviewPath) {
      const warningEl = containerEl.createEl("div", { cls: "setting-item-description" });
      warningEl.style.padding = "8px 12px";
      warningEl.style.backgroundColor = "var(--background-modifier-error)";
      warningEl.style.color = "var(--text-error)";
      warningEl.style.borderRadius = "4px";
      warningEl.style.marginBottom = "15px";
      warningEl.textContent = "\u26A0 Please specify a path for weekly review";
    }
  }
  displaySchedulingSettings(containerEl) {
    containerEl.createEl("h2", { text: "\u23F0 Scheduling" });
    new import_obsidian.Setting(containerEl).setName("Meeting Debrief Lead Time").setDesc("Minutes before a meeting to generate the debrief").addSlider((slider) => slider.setLimits(5, 60, 5).setValue(this.plugin.settings.meetingPrepMinutesBefore).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.meetingPrepMinutesBefore = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Sync Interval").setDesc("Minutes between Google Calendar/Gmail syncs").addSlider((slider) => slider.setLimits(5, 60, 5).setValue(this.plugin.settings.syncInterval).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.syncInterval = value;
      await this.plugin.saveSettings();
    }));
  }
  displayFeatureToggles(containerEl) {
    containerEl.createEl("h2", { text: "\u{1F39B}\uFE0F Feature Toggles" });
    new import_obsidian.Setting(containerEl).setName("Enable Inbox Triage").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableInboxTriage).onChange(async (value) => {
      this.plugin.settings.enableInboxTriage = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable Meeting Prep Debriefs").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableMeetingPrep).onChange(async (value) => {
      this.plugin.settings.enableMeetingPrep = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable Weekly Time Audit").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableTimeAudit).onChange(async (value) => {
      this.plugin.settings.enableTimeAudit = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable Daily Standup (9 AM)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableDailyStandup).onChange(async (value) => {
      this.plugin.settings.enableDailyStandup = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable Evening Journal (9 PM)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableEveningJournal).onChange(async (value) => {
      this.plugin.settings.enableEveningJournal = value;
      await this.plugin.saveSettings();
    }));
  }
  displayAdvancedLLMConfig(containerEl) {
    containerEl.createEl("h2", { text: "\u{1F9E0} Advanced LLM & RAG Configuration" });
    new import_obsidian.Setting(containerEl).setName("Instructions System Prompt Path").setDesc("Vault path to instructions.md file that defines AI behavior").addText((text) => text.setPlaceholder("Chief of Staff/instructions.md").setValue(this.plugin.settings.instructionsPath).onChange(async (value) => {
      this.plugin.settings.instructionsPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Voice Mirroring Style Path").setDesc("Vault path to a markdown file explaining your writing style").addText((text) => text.setPlaceholder("Chief of Staff/Voice Style.md").setValue(this.plugin.settings.voiceMirrorPath).onChange(async (value) => {
      this.plugin.settings.voiceMirrorPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Personal Contacts Folder").setDesc("Folder for personal people notes").addText((text) => text.setPlaceholder("People/Personal").setValue(this.plugin.settings.personalContactsFolder).onChange(async (value) => {
      this.plugin.settings.personalContactsFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Work Contacts Folder").setDesc("Folder for work people notes").addText((text) => text.setPlaceholder("People/Work").setValue(this.plugin.settings.workContactsFolder).onChange(async (value) => {
      this.plugin.settings.workContactsFolder = value;
      await this.plugin.saveSettings();
    }));
  }
  displayEmailCalendarRules(containerEl) {
    containerEl.createEl("h2", { text: "\u{1F4E7} Email & Calendar Rules" });
    new import_obsidian.Setting(containerEl).setName("Archive Threshold (Days)").setDesc("Emails older than this limit will be batched into the digest").addText((text) => {
      var _a;
      return text.setPlaceholder("90").setValue(((_a = this.plugin.settings.archiveThresholdDays) == null ? void 0 : _a.toString()) || "90").onChange(async (value) => {
        this.plugin.settings.archiveThresholdDays = parseInt(value, 10) || 90;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Newsletter Domains").setDesc("Comma-separated domains to process as newsletters").addTextArea((text) => {
      text.setPlaceholder("substack.com, medium.com").setValue(this.plugin.settings.newsletterDomains).onChange(async (value) => {
        this.plugin.settings.newsletterDomains = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.style.width = "100%";
      text.inputEl.rows = 3;
    });
    new import_obsidian.Setting(containerEl).setName("Personal Event Keywords").setDesc("Comma-separated keywords to identify personal meetings (ignored by Work Prep)").addText((text) => text.setPlaceholder("Lunch, Gym, Personal").setValue(this.plugin.settings.personalEventKeywords).onChange(async (value) => {
      this.plugin.settings.personalEventKeywords = value;
      await this.plugin.saveSettings();
    }));
  }
  displayBackgroundServiceConfig(containerEl) {
    containerEl.createEl("h2", { text: "\u2699\uFE0F Background Service Daemon" });
    const infoEl = containerEl.createEl("div", { cls: "setting-item-description" });
    infoEl.style.marginBottom = "15px";
    infoEl.style.padding = "10px";
    infoEl.style.backgroundColor = "var(--background-secondary)";
    infoEl.style.borderRadius = "5px";
    infoEl.innerHTML = `This installs the Native OS Daemon (launchd/cron/schtasks) so AI Chief of Staff runs automatically 
    in the background, even when Obsidian is closed.`;
    new import_obsidian.Setting(containerEl).setName("Triage Interval (Hours)").setDesc("How often to run the background triage").addDropdown((dropdown) => {
      var _a;
      return dropdown.addOptions({ "1": "Every Hour", "2": "Every 2 Hours", "4": "Every 4 Hours", "8": "Every 8 Hours" }).setValue(((_a = this.plugin.settings.triageIntervalHours) == null ? void 0 : _a.toString()) || "4").onChange(async (value) => {
        this.plugin.settings.triageIntervalHours = parseInt(value, 10);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Install Background Service").setDesc("Generates and registers the background OS task based on your configured times").addButton((button) => button.setButtonText("Install / Update Service").setCta().onClick(async () => {
      button.setButtonText("Installing...");
      button.setDisabled(true);
      try {
        const { exec } = window.require("child_process");
        const path = window.require("path");
        const pluginDir = this.app.vault.adapter.getBasePath() + "/.obsidian/plugins/ai-chief-of-staff/backend";
        exec(`node "${path.join(pluginDir, "setup-service.mjs")}" "${this.app.vault.adapter.getBasePath()}"`, (error, stdout, stderr) => {
          if (error) {
            new import_obsidian.Notice("Failed to install service: " + error.message);
            console.error(stderr);
          } else {
            new import_obsidian.Notice("\u2705 Background service installed successfully!");
          }
          button.setButtonText("Install / Update Service");
          button.setDisabled(false);
        });
      } catch (e) {
        new import_obsidian.Notice("Setup error: " + String(e));
        button.setButtonText("Install / Update Service");
        button.setDisabled(false);
      }
    }));
  }
};

// src/services/ollama.ts
var import_obsidian2 = require("obsidian");
var CHIEF_OF_STAFF_SYSTEM_PROMPT = `You are a precise Chief of Staff. You value brevity. You do not explain yourself; you execute. When analyzing text, prioritize actionable facts over sentiment. Only use provided context. If information is unknown, state 'No Data'. Never invent or hallucinate details.`;
var OllamaService = class {
  constructor(baseUrl, model) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.model = model;
  }
  updateConfig(baseUrl, model) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.model = model;
  }
  async testConnection() {
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url: `${this.baseUrl}/api/tags`,
        method: "GET"
      });
      return response.status === 200;
    } catch (error) {
      console.error("Ollama connection test failed:", error);
      return false;
    }
  }
  async listModels() {
    var _a;
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url: `${this.baseUrl}/api/tags`,
        method: "GET"
      });
      const data = response.json;
      return ((_a = data.models) == null ? void 0 : _a.map((m) => m.name)) || [];
    } catch (error) {
      console.error("Failed to list Ollama models:", error);
      return [];
    }
  }
  async generate(prompt, systemPrompt, jsonMode = false) {
    const request = {
      model: this.model,
      prompt,
      system: systemPrompt || CHIEF_OF_STAFF_SYSTEM_PROMPT,
      stream: false
    };
    if (jsonMode) {
      request.format = "json";
    }
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url: `${this.baseUrl}/api/generate`,
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(request)
      });
      const data = response.json;
      return data.response;
    } catch (error) {
      console.error("Ollama generate failed:", error);
      throw new Error(`Failed to generate response from Ollama: ${error}`);
    }
  }
  async summarizeNote(content) {
    const prompt = `Summarize the following note concisely, highlighting key points, decisions, and action items:

---
${this.truncateContent(content, 6e3)}
---

Provide a structured summary with:
- Key Points (bullet points)
- Decisions Made (if any)
- Action Items (if any)
- Next Steps (if any)`;
    return this.generate(prompt);
  }
  async synthesizeMeetingBrief(eventTitle, eventDescription, attendees, relatedNotes) {
    const notesContext = relatedNotes.length > 0 ? relatedNotes.map((n, i) => `[Note ${i + 1}]: ${this.truncateContent(n, 1500)}`).join("\n\n") : "No related notes found in vault.";
    const prompt = `Prepare a meeting brief for the following event:

**Meeting:** ${eventTitle}
**Description:** ${eventDescription || "No description provided"}
**Attendees:** ${attendees.join(", ") || "No attendees listed"}

**Related Context from Vault:**
${notesContext}

Generate a briefing note with:
1. **Context**: Who are the attendees? Any relevant background from notes?
2. **History**: Summary of previous discussions with these people/topics
3. **Talking Points**: 3-5 suggested agenda items based on context
4. **Open Questions**: Things that need resolution`;
    return this.generate(prompt);
  }
  async classifyEmails(emails) {
    if (emails.length === 0)
      return [];
    const emailList = emails.map(
      (e, i) => `[${i}] From: ${e.from}
Subject: ${e.subject}
Preview: ${e.snippet.substring(0, 200)}`
    ).join("\n\n---\n\n");
    const prompt = `Classify each email into one of three categories:
- URGENT: Requires immediate action, time-sensitive, from important contacts
- REVIEW: Worth reading later, not urgent but potentially valuable
- NOISE: Newsletters, promotions, automated messages, low priority

Emails to classify:
${emailList}

Respond in JSON format:
{
  "classifications": [
    {"id": 0, "classification": "URGENT|REVIEW|NOISE", "reason": "brief reason"},
    ...
  ]
}`;
    const response = await this.generate(prompt, void 0, true);
    try {
      const parsed = JSON.parse(response);
      return parsed.classifications || [];
    } catch (e) {
      console.error("Failed to parse email classification response");
      return emails.map((_, i) => ({ id: i, classification: "REVIEW", reason: "Classification failed" }));
    }
  }
  async categorizeEvents(events) {
    if (events.length === 0)
      return [];
    const eventList = events.map((e) => `[${e.id}] "${e.summary}" (${e.duration.toFixed(1)}h)`).join("\n");
    const prompt = `Categorize the following calendar events into high-level categories like:
- Deep Work (focused, creative, coding, writing)
- Admin (emails, paperwork, scheduling)
- Meetings (external calls, client meetings)
- Internal (team meetings, 1:1s, standups)
- Personal (breaks, appointments, errands)

Events from last 7 days (format: [id] "title" (duration)):
${eventList}

For each category, provide the list of event IDs (the numbers in brackets) that belong to it.

Respond in JSON format:
{
  "categories": [
    {"name": "Category Name", "eventIds": [0, 2, 5]},
    ...
  ]
}`;
    const response = await this.generate(prompt, void 0, true);
    try {
      const parsed = JSON.parse(response);
      const eventDurationMap = new Map(events.map((e) => [e.id, e.duration]));
      return (parsed.categories || []).map((cat) => {
        const eventIndices = cat.eventIds || [];
        const totalHours = eventIndices.reduce((sum, id) => sum + (eventDurationMap.get(id) || 0), 0);
        return {
          category: cat.name,
          eventIndices,
          totalHours
        };
      });
    } catch (e) {
      console.error("Failed to parse event categorization response");
      return [];
    }
  }
  async draftEmailReply(originalEmail, vaultContext, instructions) {
    const prompt = `Draft a professional email reply.

**Original Email:**
From: ${originalEmail.from}
Subject: ${originalEmail.subject}
Body: ${this.truncateContent(originalEmail.body, 2e3)}

**Context from your notes:**
${this.truncateContent(vaultContext, 2e3)}

${instructions ? `**Special Instructions:** ${instructions}` : ""}

Write a concise, professional reply. Use the context from notes to inform your response. Be helpful but brief.`;
    return this.generate(prompt);
  }
  async queryVaultWithContext(query, relevantChunks) {
    const context = relevantChunks.length > 0 ? relevantChunks.map((c, i) => `[Chunk ${i + 1}]: ${this.truncateContent(c, 1500)}`).join("\n\n") : "No relevant content found.";
    const prompt = `Answer the following query using ONLY the provided context. If the answer cannot be found in the context, say "No relevant information found in vault."

**Query:** ${query}

**Context from Vault:**
${context}

Provide a clear, concise answer based strictly on the provided context.`;
    return this.generate(prompt);
  }
  truncateContent(content, maxChars) {
    if (content.length <= maxChars)
      return content;
    return content.substring(0, maxChars) + "... [truncated]";
  }
};

// src/services/google-auth.ts
var import_obsidian3 = require("obsidian");
var GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth";
var GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";
var SCOPES = [
  "https://www.googleapis.com/auth/calendar.readonly",
  "https://www.googleapis.com/auth/gmail.readonly",
  "https://www.googleapis.com/auth/gmail.modify"
].join(" ");
var GoogleAuthService = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  generateAuthUrl() {
    const { googleClientId } = this.plugin.settings;
    if (!googleClientId) {
      throw new Error("Google Client ID not configured");
    }
    const params = new URLSearchParams({
      client_id: googleClientId,
      redirect_uri: "urn:ietf:wg:oauth:2.0:oob",
      response_type: "code",
      scope: SCOPES,
      access_type: "offline",
      prompt: "consent"
    });
    return `${GOOGLE_AUTH_URL}?${params.toString()}`;
  }
  async exchangeCodeForTokens(code) {
    const { googleClientId, googleClientSecret } = this.plugin.settings;
    if (!googleClientId || !googleClientSecret) {
      throw new Error("Google credentials not configured");
    }
    const response = await (0, import_obsidian3.requestUrl)({
      url: GOOGLE_TOKEN_URL,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: new URLSearchParams({
        code,
        client_id: googleClientId,
        client_secret: googleClientSecret,
        redirect_uri: "urn:ietf:wg:oauth:2.0:oob",
        grant_type: "authorization_code"
      }).toString()
    });
    const data = response.json;
    this.plugin.settings.googleAccessToken = data.access_token;
    this.plugin.settings.googleRefreshToken = data.refresh_token || this.plugin.settings.googleRefreshToken;
    this.plugin.settings.googleTokenExpiry = Date.now() + data.expires_in * 1e3;
    await this.plugin.saveSettings();
  }
  async refreshAccessToken() {
    const { googleClientId, googleClientSecret, googleRefreshToken } = this.plugin.settings;
    if (!googleRefreshToken) {
      throw new Error("No refresh token available. Please re-authenticate.");
    }
    const response = await (0, import_obsidian3.requestUrl)({
      url: GOOGLE_TOKEN_URL,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: new URLSearchParams({
        client_id: googleClientId,
        client_secret: googleClientSecret,
        refresh_token: googleRefreshToken,
        grant_type: "refresh_token"
      }).toString()
    });
    const data = response.json;
    this.plugin.settings.googleAccessToken = data.access_token;
    this.plugin.settings.googleTokenExpiry = Date.now() + data.expires_in * 1e3;
    await this.plugin.saveSettings();
    return data.access_token;
  }
  async getValidAccessToken() {
    const { googleAccessToken, googleTokenExpiry } = this.plugin.settings;
    if (!googleAccessToken) {
      throw new Error("Not authenticated. Please login to Google.");
    }
    if (Date.now() >= googleTokenExpiry - 6e4) {
      return this.refreshAccessToken();
    }
    return googleAccessToken;
  }
  isAuthenticated() {
    return !!(this.plugin.settings.googleAccessToken && this.plugin.settings.googleRefreshToken);
  }
  async logout() {
    this.plugin.settings.googleAccessToken = "";
    this.plugin.settings.googleRefreshToken = "";
    this.plugin.settings.googleTokenExpiry = 0;
    this.plugin.settings.calendarSyncToken = "";
    this.plugin.settings.gmailHistoryId = "";
    await this.plugin.saveSettings();
  }
};

// src/services/calendar.ts
var import_obsidian4 = require("obsidian");
var CALENDAR_API_BASE = "https://www.googleapis.com/calendar/v3";
var CalendarService = class {
  constructor(authService) {
    this.rateLimitBackoff = 1e3;
    this.authService = authService;
  }
  async fetchEvents(timeMin, timeMax) {
    const accessToken = await this.authService.getValidAccessToken();
    const params = new URLSearchParams({
      timeMin: timeMin.toISOString(),
      timeMax: timeMax.toISOString(),
      singleEvents: "true",
      orderBy: "startTime",
      maxResults: "250"
    });
    try {
      const response = await (0, import_obsidian4.requestUrl)({
        url: `${CALENDAR_API_BASE}/calendars/primary/events?${params.toString()}`,
        method: "GET",
        headers: {
          "Authorization": `Bearer ${accessToken}`
        }
      });
      const data = response.json;
      this.rateLimitBackoff = 1e3;
      return (data.items || []).map(this.parseEvent);
    } catch (error) {
      if (this.isRateLimitError(error)) {
        await this.handleRateLimit();
        return this.fetchEvents(timeMin, timeMax);
      }
      throw error;
    }
  }
  async fetchUpcomingEvents(minutesAhead = 60) {
    const now = /* @__PURE__ */ new Date();
    const future = new Date(now.getTime() + minutesAhead * 60 * 1e3);
    return this.fetchEvents(now, future);
  }
  async fetchTodayEvents() {
    const now = /* @__PURE__ */ new Date();
    const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const endOfDay = new Date(startOfDay.getTime() + 24 * 60 * 60 * 1e3);
    return this.fetchEvents(startOfDay, endOfDay);
  }
  async fetchWeekEvents() {
    const now = /* @__PURE__ */ new Date();
    const startOfWeek = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1e3);
    return this.fetchEvents(startOfWeek, now);
  }
  parseEvent(item) {
    const start = item.start;
    const end = item.end;
    const attendees = item.attendees;
    return {
      id: item.id,
      summary: item.summary || "No Title",
      description: item.description,
      start: new Date((start == null ? void 0 : start.dateTime) || (start == null ? void 0 : start.date) || ""),
      end: new Date((end == null ? void 0 : end.dateTime) || (end == null ? void 0 : end.date) || ""),
      attendees: (attendees == null ? void 0 : attendees.map((a) => a.email)) || [],
      location: item.location
    };
  }
  isRateLimitError(error) {
    return error instanceof Error && error.message.includes("429");
  }
  async handleRateLimit() {
    console.warn(`Rate limited. Backing off for ${this.rateLimitBackoff}ms`);
    await new Promise((resolve) => setTimeout(resolve, this.rateLimitBackoff));
    this.rateLimitBackoff = Math.min(this.rateLimitBackoff * 2, 6e4);
  }
};

// src/services/gmail.ts
var import_obsidian5 = require("obsidian");
var GMAIL_API_BASE = "https://www.googleapis.com/gmail/v1";
var GmailService = class {
  constructor(authService) {
    this.rateLimitBackoff = 1e3;
    this.authService = authService;
  }
  async fetchUnreadEmails(maxResults = 20) {
    const accessToken = await this.authService.getValidAccessToken();
    const params = new URLSearchParams({
      q: "is:unread",
      maxResults: maxResults.toString()
    });
    try {
      const response = await (0, import_obsidian5.requestUrl)({
        url: `${GMAIL_API_BASE}/users/me/messages?${params.toString()}`,
        method: "GET",
        headers: {
          "Authorization": `Bearer ${accessToken}`
        }
      });
      const data = response.json;
      this.rateLimitBackoff = 1e3;
      if (!data.messages || data.messages.length === 0) {
        return [];
      }
      const emails = [];
      for (const msg of data.messages.slice(0, maxResults)) {
        const email = await this.fetchEmailDetails(msg.id, accessToken);
        if (email)
          emails.push(email);
      }
      return emails;
    } catch (error) {
      if (this.isRateLimitError(error)) {
        await this.handleRateLimit();
        return this.fetchUnreadEmails(maxResults);
      }
      throw error;
    }
  }
  async fetchEmailDetails(messageId, accessToken) {
    var _a;
    try {
      const response = await (0, import_obsidian5.requestUrl)({
        url: `${GMAIL_API_BASE}/users/me/messages/${messageId}?format=metadata&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date`,
        method: "GET",
        headers: {
          "Authorization": `Bearer ${accessToken}`
        }
      });
      const data = response.json;
      const headers = ((_a = data.payload) == null ? void 0 : _a.headers) || [];
      const getHeader = (name) => {
        const header = headers.find(
          (h) => h.name.toLowerCase() === name.toLowerCase()
        );
        return (header == null ? void 0 : header.value) || "";
      };
      return {
        id: data.id,
        threadId: data.threadId,
        from: getHeader("From"),
        subject: getHeader("Subject"),
        snippet: data.snippet || "",
        date: new Date(parseInt(data.internalDate)),
        labels: data.labelIds || []
      };
    } catch (error) {
      console.error(`Failed to fetch email ${messageId}:`, error);
      return null;
    }
  }
  async fetchEmailBody(messageId) {
    const accessToken = await this.authService.getValidAccessToken();
    try {
      const response = await (0, import_obsidian5.requestUrl)({
        url: `${GMAIL_API_BASE}/users/me/messages/${messageId}?format=full`,
        method: "GET",
        headers: {
          "Authorization": `Bearer ${accessToken}`
        }
      });
      const data = response.json;
      return this.extractBody(data.payload);
    } catch (error) {
      console.error(`Failed to fetch email body ${messageId}:`, error);
      return "";
    }
  }
  extractBody(payload) {
    if (payload.body && payload.body.data) {
      return this.decodeBase64(payload.body.data);
    }
    const parts = payload.parts;
    if (parts) {
      for (const part of parts) {
        const mimeType = part.mimeType;
        if (mimeType === "text/plain") {
          const body = part.body;
          if (body == null ? void 0 : body.data) {
            return this.decodeBase64(body.data);
          }
        }
        if (part.parts) {
          const nested = this.extractBody(part);
          if (nested)
            return nested;
        }
      }
    }
    return "";
  }
  decodeBase64(encoded) {
    try {
      const decoded = atob(encoded.replace(/-/g, "+").replace(/_/g, "/"));
      return decoded;
    } catch (e) {
      return "";
    }
  }
  isRateLimitError(error) {
    return error instanceof Error && error.message.includes("429");
  }
  async handleRateLimit() {
    console.warn(`Rate limited. Backing off for ${this.rateLimitBackoff}ms`);
    await new Promise((resolve) => setTimeout(resolve, this.rateLimitBackoff));
    this.rateLimitBackoff = Math.min(this.rateLimitBackoff * 2, 6e4);
  }
};

// src/services/smart-connections.ts
var SmartConnectionsService = class {
  constructor(app) {
    this.app = app;
  }
  isAvailable() {
    var _a, _b;
    const appWithPlugins = this.app;
    return !!((_b = (_a = appWithPlugins.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b["smart-connections"]);
  }
  getPlugin() {
    var _a, _b;
    const appWithPlugins = this.app;
    return ((_b = (_a = appWithPlugins.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b["smart-connections"]) || null;
  }
  async search(query, limit = 5) {
    var _a;
    const sc = this.getPlugin();
    if (!((_a = sc == null ? void 0 : sc.api) == null ? void 0 : _a.search)) {
      console.warn("Smart Connections plugin not available or API not exposed");
      return this.fallbackSearch(query, limit);
    }
    try {
      const results = await sc.api.search(query, { limit });
      return results.map((r) => ({
        path: r.path,
        content: r.text,
        score: r.score
      }));
    } catch (error) {
      console.error("Smart Connections search failed:", error);
      return this.fallbackSearch(query, limit);
    }
  }
  async fallbackSearch(query, limit) {
    const files = this.app.vault.getMarkdownFiles();
    const queryTerms = query.toLowerCase().split(/\s+/);
    const results = [];
    for (const file of files.slice(0, 100)) {
      try {
        const content = await this.app.vault.cachedRead(file);
        const contentLower = content.toLowerCase();
        let score = 0;
        for (const term of queryTerms) {
          if (contentLower.includes(term))
            score++;
          if (file.basename.toLowerCase().includes(term))
            score += 2;
        }
        if (score > 0) {
          results.push({
            path: file.path,
            content: content.substring(0, 2e3),
            score
          });
        }
      } catch (e) {
        continue;
      }
    }
    results.sort((a, b) => b.score - a.score);
    return results.slice(0, limit);
  }
  async getRelatedNotes(context, limit = 3) {
    const results = await this.search(context, limit);
    return results.map((r) => r.content);
  }
  async searchForPerson(name) {
    const results = await this.search(name, 3);
    return results.map((r) => r.content);
  }
  async searchForTopic(topic) {
    const results = await this.search(topic, 5);
    return results.map((r) => r.content);
  }
};

// src/features/meeting-prep.ts
var MeetingPrepFeature = class {
  constructor(app, ollama, calendar, smartConnections, dailyNotePath) {
    this.checkIntervalId = null;
    this.processedEvents = /* @__PURE__ */ new Set();
    this.app = app;
    this.ollama = ollama;
    this.calendar = calendar;
    this.smartConnections = smartConnections;
    this.dailyNotePath = dailyNotePath;
  }
  updateConfig(dailyNotePath) {
    this.dailyNotePath = dailyNotePath;
  }
  startAutoCheck(minutesBefore = 15) {
    if (this.checkIntervalId) {
      window.clearInterval(this.checkIntervalId);
    }
    this.checkIntervalId = window.setInterval(async () => {
      await this.checkUpcomingMeetings(minutesBefore);
    }, 6e4);
    this.checkUpcomingMeetings(minutesBefore);
  }
  stopAutoCheck() {
    if (this.checkIntervalId) {
      window.clearInterval(this.checkIntervalId);
      this.checkIntervalId = null;
    }
  }
  async checkUpcomingMeetings(minutesBefore = 15) {
    try {
      const events = await this.calendar.fetchUpcomingEvents(minutesBefore);
      for (const event of events) {
        if (this.processedEvents.has(event.id))
          continue;
        const minutesUntil = (event.start.getTime() - Date.now()) / 6e4;
        if (minutesUntil <= minutesBefore && minutesUntil > 0) {
          await this.generateBriefForEvent(event);
          this.processedEvents.add(event.id);
        }
      }
      const yesterday = Date.now() - 24 * 60 * 60 * 1e3;
      for (const eventId of this.processedEvents) {
        const timestamp = parseInt(eventId.split("_")[0] || "0");
        if (timestamp < yesterday) {
          this.processedEvents.delete(eventId);
        }
      }
    } catch (error) {
      console.error("Failed to check upcoming meetings:", error);
    }
  }
  async generateBriefForEvent(event) {
    const searchQueries = [
      event.summary,
      ...event.attendees.slice(0, 3)
    ].filter(Boolean);
    const relatedNotes = [];
    for (const query of searchQueries) {
      const notes = await this.smartConnections.getRelatedNotes(query, 2);
      relatedNotes.push(...notes);
    }
    const uniqueNotes = [...new Set(relatedNotes)].slice(0, 5);
    const briefContent = await this.ollama.synthesizeMeetingBrief(
      event.summary,
      event.description || "",
      event.attendees,
      uniqueNotes
    );
    const brief = {
      eventTitle: event.summary,
      attendees: event.attendees,
      context: briefContent,
      history: "",
      talkingPoints: [],
      generatedAt: /* @__PURE__ */ new Date()
    };
    await this.writeBriefToDaily(event, briefContent);
    return brief;
  }
  async generateBriefManually() {
    const events = await this.calendar.fetchTodayEvents();
    const now = /* @__PURE__ */ new Date();
    const upcomingEvents = events.filter((e) => e.start > now);
    if (upcomingEvents.length === 0) {
      throw new Error("No upcoming events found for today");
    }
    const nextEvent = upcomingEvents[0];
    await this.generateBriefForEvent(nextEvent);
  }
  async writeBriefToDaily(event, briefContent) {
    const today = /* @__PURE__ */ new Date();
    const dateStr = today.toISOString().split("T")[0];
    const dailyNoteName = `${dateStr}.md`;
    const dailyNotePath = `${this.dailyNotePath}/${dailyNoteName}`;
    const briefSection = `

---

## \u{1F4CB} Meeting Brief: ${event.summary}

**Time:** ${event.start.toLocaleTimeString()} - ${event.end.toLocaleTimeString()}
**Attendees:** ${event.attendees.join(", ") || "None listed"}
${event.location ? `**Location:** ${event.location}` : ""}

### Briefing

${briefContent}

*Generated at ${(/* @__PURE__ */ new Date()).toLocaleTimeString()}*

---
`;
    let file = this.app.vault.getAbstractFileByPath(dailyNotePath);
    if (!file) {
      const folderPath = this.dailyNotePath;
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (!folder) {
        await this.app.vault.createFolder(folderPath);
      }
      await this.app.vault.create(dailyNotePath, `# ${dateStr}
${briefSection}`);
    } else if (file instanceof this.app.vault.adapter.constructor) {
      const content = await this.app.vault.read(file);
      await this.app.vault.modify(file, content + briefSection);
    } else {
      const tFile = file;
      const content = await this.app.vault.read(tFile);
      await this.app.vault.modify(tFile, content + briefSection);
    }
  }
};

// src/features/inbox-triage.ts
var InboxTriageFeature = class {
  constructor(app, ollama, gmail, smartConnections, inboxNotePath) {
    this.autoTriageIntervalId = null;
    this.app = app;
    this.ollama = ollama;
    this.gmail = gmail;
    this.smartConnections = smartConnections;
    this.inboxNotePath = inboxNotePath;
  }
  updateConfig(inboxNotePath) {
    this.inboxNotePath = inboxNotePath;
  }
  startAutoTriage(intervalMinutes = 60) {
    if (this.autoTriageIntervalId) {
      window.clearInterval(this.autoTriageIntervalId);
    }
    this.autoTriageIntervalId = window.setInterval(async () => {
      await this.triageInbox();
    }, intervalMinutes * 60 * 1e3);
  }
  stopAutoTriage() {
    if (this.autoTriageIntervalId) {
      window.clearInterval(this.autoTriageIntervalId);
      this.autoTriageIntervalId = null;
    }
  }
  async triageInbox() {
    const emails = await this.gmail.fetchUnreadEmails(20);
    if (emails.length === 0) {
      await this.writeTriageNote([]);
      return [];
    }
    const emailsForClassification = emails.map((e) => ({
      from: e.from,
      subject: e.subject,
      snippet: e.snippet
    }));
    const classifications = await this.ollama.classifyEmails(emailsForClassification);
    const classifiedEmails = emails.map((email, index) => {
      var _a;
      return {
        ...email,
        classification: ((_a = classifications.find((c) => c.id === index)) == null ? void 0 : _a.classification) || "REVIEW"
      };
    });
    await this.writeTriageNote(classifiedEmails);
    return classifiedEmails;
  }
  async draftReply(email, instructions) {
    const emailBody = await this.gmail.fetchEmailBody(email.id);
    const searchQueries = [
      email.from.split("<")[0].trim(),
      email.subject
    ];
    const vaultContext = [];
    for (const query of searchQueries) {
      const notes = await this.smartConnections.getRelatedNotes(query, 2);
      vaultContext.push(...notes);
    }
    const draft = await this.ollama.draftEmailReply(
      {
        from: email.from,
        subject: email.subject,
        body: emailBody
      },
      vaultContext.join("\n\n---\n\n"),
      instructions
    );
    return draft;
  }
  async writeTriageNote(emails) {
    const now = /* @__PURE__ */ new Date();
    const timestamp = now.toLocaleString();
    const urgentEmails = emails.filter((e) => e.classification === "URGENT");
    const reviewEmails = emails.filter((e) => e.classification === "REVIEW");
    const noiseEmails = emails.filter((e) => e.classification === "NOISE");
    const formatEmail = (e) => {
      const date = e.date.toLocaleDateString();
      return `- [ ] **${e.subject}**
  - From: ${e.from}
  - Date: ${date}
  - Preview: ${e.snippet.substring(0, 100)}...
  - ID: \`${e.id}\``;
    };
    const urgentSection = urgentEmails.length > 0 ? `> [!danger] \u{1F534} URGENT - Requires Immediate Attention
${urgentEmails.map((e) => `> ${formatEmail(e)}`).join("\n>\n")}` : "> [!success] No urgent emails";
    const reviewSection = reviewEmails.length > 0 ? `> [!warning] \u{1F7E1} REVIEW - Needs Your Response
${reviewEmails.map((e) => `> ${formatEmail(e)}`).join("\n>\n")}` : "> [!success] No emails to review";
    const noiseSection = noiseEmails.length > 0 ? `> [!info] \u{1F7E2} NOISE - Low Priority
${noiseEmails.map((e) => `> ${formatEmail(e)}`).join("\n>\n")}` : "> [!success] No noise emails";
    const content = `# \u{1F4EC} Inbox Triage

*Last updated: ${timestamp}*

> [!abstract] Summary
> - **Total Unread:** ${emails.length}
> - \u{1F534} Urgent: ${urgentEmails.length} (${emails.length > 0 ? Math.round(urgentEmails.length / emails.length * 100) : 0}%)
> - \u{1F7E1} Review: ${reviewEmails.length} (${emails.length > 0 ? Math.round(reviewEmails.length / emails.length * 100) : 0}%)
> - \u{1F7E2} Noise: ${noiseEmails.length} (${emails.length > 0 ? Math.round(noiseEmails.length / emails.length * 100) : 0}%)

---

## \u{1F6A8} URGENT (${urgentEmails.length})

${urgentSection}

---

## \u{1F4D6} REVIEW (${reviewEmails.length})

${reviewSection}

---

## \u{1F507} NOISE (${noiseEmails.length})

<details>
<summary>Click to expand noise emails</summary>

${noiseSection}

</details>

---

> [!tip] Next Steps
> - [ ] Address urgent emails first
> - [ ] Schedule time for review items
> - [ ] Archive or delete noise

*Generated by AI Chief of Staff*
`;
    let file = this.app.vault.getAbstractFileByPath(this.inboxNotePath);
    if (!file) {
      await this.app.vault.create(this.inboxNotePath, content);
    } else {
      await this.app.vault.modify(file, content);
    }
  }
};

// src/features/time-audit.ts
var TimeAuditFeature = class {
  constructor(app, ollama, calendar, weeklyReviewPath) {
    this.app = app;
    this.ollama = ollama;
    this.calendar = calendar;
    this.weeklyReviewPath = weeklyReviewPath;
  }
  updateConfig(weeklyReviewPath) {
    this.weeklyReviewPath = weeklyReviewPath;
  }
  async generateTimeAudit() {
    const events = await this.calendar.fetchWeekEvents();
    if (events.length === 0) {
      throw new Error("No calendar events found for the past week");
    }
    const eventsWithDuration = events.map((e, index) => ({
      id: index,
      summary: e.summary,
      duration: (e.end.getTime() - e.start.getTime()) / (1e3 * 60 * 60)
    }));
    const totalHours = eventsWithDuration.reduce((sum, e) => sum + e.duration, 0);
    const categorizedData = await this.ollama.categorizeEvents(eventsWithDuration);
    const categories = categorizedData.map((cat) => {
      const percentage = totalHours > 0 ? Math.round(cat.totalHours / totalHours * 100) : 0;
      const eventNames = cat.eventIndices.map((idx) => {
        var _a;
        return ((_a = eventsWithDuration[idx]) == null ? void 0 : _a.summary) || "Unknown";
      });
      return {
        name: cat.category,
        hours: cat.totalHours,
        percentage,
        events: eventNames
      };
    });
    await this.writeWeeklyReview(events, categories, totalHours);
    return categories;
  }
  async writeWeeklyReview(events, categories, totalHours) {
    const now = /* @__PURE__ */ new Date();
    const weekStart = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1e3);
    const dateRange = `${weekStart.toLocaleDateString()} - ${now.toLocaleDateString()}`;
    const mermaidChart = this.generateMermaidPieChart(categories);
    const categoriesTable = this.generateCategoriesTable(categories);
    const eventsList = this.generateEventsList(events);
    const content = `# \u{1F4CA} Weekly Time Audit

*Period: ${dateRange}*
*Generated: ${now.toLocaleString()}*

## Time Distribution

\`\`\`mermaid
${mermaidChart}
\`\`\`

## Categories Breakdown

${categoriesTable}

## Summary

- **Total Scheduled Time:** ${totalHours.toFixed(1)} hours
- **Total Events:** ${events.length}
- **Average Event Duration:** ${(totalHours / events.length).toFixed(1)} hours

## All Events This Week

${eventsList}

---

### Insights

Based on your time allocation this week:

${this.generateInsights(categories)}

---

*This report was generated by AI Chief of Staff*
`;
    let file = this.app.vault.getAbstractFileByPath(this.weeklyReviewPath);
    if (!file) {
      await this.app.vault.create(this.weeklyReviewPath, content);
    } else {
      await this.app.vault.modify(file, content);
    }
  }
  generateMermaidPieChart(categories) {
    const pieData = categories.filter((c) => c.percentage > 0).map((c) => `    "${c.name}" : ${c.percentage}`).join("\n");
    return `pie showData
    title Time Allocation
${pieData}`;
  }
  generateCategoriesTable(categories) {
    const rows = categories.map((c) => {
      return `| ${c.name} | ${c.hours.toFixed(1)}h | ${c.percentage}% | ${c.events.length} |`;
    }).join("\n");
    return `| Category | Hours | Percentage | Events |
|----------|-------|------------|--------|
${rows}`;
  }
  generateEventsList(events) {
    const sortedEvents = [...events].sort((a, b) => a.start.getTime() - b.start.getTime());
    return sortedEvents.map((e) => {
      const date = e.start.toLocaleDateString();
      const time = e.start.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
      const duration = ((e.end.getTime() - e.start.getTime()) / (1e3 * 60 * 60)).toFixed(1);
      return `- **${e.summary}** - ${date} ${time} (${duration}h)`;
    }).join("\n");
  }
  generateInsights(categories) {
    const sorted = [...categories].sort((a, b) => b.percentage - a.percentage);
    const insights = [];
    if (sorted.length > 0) {
      insights.push(`- Your largest time allocation was **${sorted[0].name}** at ${sorted[0].percentage}% of your scheduled time.`);
    }
    const deepWork = sorted.find((c) => c.name.toLowerCase().includes("deep") || c.name.toLowerCase().includes("focus"));
    if (deepWork) {
      if (deepWork.percentage < 20) {
        insights.push(`- Consider blocking more time for deep work. Currently only ${deepWork.percentage}% of your time.`);
      } else {
        insights.push(`- Good focus time allocation with ${deepWork.percentage}% in deep work.`);
      }
    }
    const meetings = sorted.find((c) => c.name.toLowerCase().includes("meeting") || c.name.toLowerCase().includes("external"));
    if (meetings && meetings.percentage > 50) {
      insights.push(`- Warning: ${meetings.percentage}% of time in meetings. Consider protecting more maker time.`);
    }
    return insights.length > 0 ? insights.join("\n") : "- No specific insights available. Review your categories manually.";
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  ollamaUrl: "http://localhost:11434",
  ollamaModel: "gemma3:4b-it-qat",
  googleClientId: "",
  googleClientSecret: "",
  googleAccessToken: "",
  googleRefreshToken: "",
  googleTokenExpiry: 0,
  syncInterval: 15,
  calendarSyncToken: "",
  gmailHistoryId: "",
  meetingPrepMinutesBefore: 15,
  dailyNotePath: "Daily Notes",
  inboxNotePath: "Inbox Triage.md",
  weeklyReviewPath: "Weekly Review.md",
  enableInboxTriage: true,
  enableMeetingPrep: true,
  enableTimeAudit: true,
  enableDailyStandup: true,
  enableEveningJournal: true,
  instructionsPath: "Chief of Staff/instructions.md",
  voiceMirrorPath: "Chief of Staff/Voice Style.md",
  personalContactsFolder: "People/Personal",
  workContactsFolder: "People/Work",
  archiveThresholdDays: 90,
  newsletterDomains: "substack.com, medium.com",
  personalEventKeywords: "Lunch, Gym, Personal",
  triageIntervalHours: 4,
  dailyStandupTime: "09:00",
  eveningJournalTime: "21:00"
};

// src/main.ts
var AIChiefOfStaffPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.statusBarItem = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerCustomIcons();
    this.initializeServices();
    this.initializeFeatures();
    this.registerCommands();
    this.registerRibbonIcons();
    this.initializeStatusBar();
    this.addSettingTab(new AIChiefOfStaffSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.startBackgroundTasks();
      this.updateStatusBar();
    });
    console.log("AI Chief of Staff plugin loaded");
  }
  registerCustomIcons() {
    (0, import_obsidian6.addIcon)("meeting-debrief", '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line><path d="M8 14h.01"></path><path d="M12 14h.01"></path><path d="M16 14h.01"></path><path d="M8 18h.01"></path><path d="M12 18h.01"></path></svg>');
    (0, import_obsidian6.addIcon)("inbox-triage", '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-6l-2 3h-4l-2-3H2"></path><path d="M5.45 5.11L2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"></path></svg>');
    (0, import_obsidian6.addIcon)("time-audit", '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21.21 15.89A10 10 0 1 1 8 2.83"></path><path d="M22 12A10 10 0 0 0 12 2v10z"></path></svg>');
    (0, import_obsidian6.addIcon)("daily-briefing", '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>');
  }
  registerRibbonIcons() {
    this.addRibbonIcon("meeting-debrief", "Generate Meeting Debrief", async () => {
      if (!this.googleAuthService.isAuthenticated()) {
        new import_obsidian6.Notice("Please connect to Google first (Settings > AI Chief of Staff)");
        return;
      }
      new import_obsidian6.Notice("Generating meeting debrief...");
      try {
        await this.meetingPrepFeature.generateBriefManually();
        new import_obsidian6.Notice("Meeting debrief generated!");
      } catch (error) {
        new import_obsidian6.Notice(`Failed: ${error instanceof Error ? error.message : String(error)}`);
      }
    });
    this.addRibbonIcon("inbox-triage", "Triage Email Inbox", async () => {
      if (!this.googleAuthService.isAuthenticated()) {
        new import_obsidian6.Notice("Please connect to Google first (Settings > AI Chief of Staff)");
        return;
      }
      new import_obsidian6.Notice("Triaging inbox...");
      try {
        const emails = await this.inboxTriageFeature.triageInbox();
        new import_obsidian6.Notice(`Triaged ${emails.length} emails`);
      } catch (error) {
        new import_obsidian6.Notice(`Failed: ${error instanceof Error ? error.message : String(error)}`);
      }
    });
    this.addRibbonIcon("time-audit", "Generate Time Audit", async () => {
      if (!this.googleAuthService.isAuthenticated()) {
        new import_obsidian6.Notice("Please connect to Google first (Settings > AI Chief of Staff)");
        return;
      }
      new import_obsidian6.Notice("Generating time audit...");
      try {
        await this.timeAuditFeature.generateTimeAudit();
        new import_obsidian6.Notice("Time audit generated!");
      } catch (error) {
        new import_obsidian6.Notice(`Failed: ${error instanceof Error ? error.message : String(error)}`);
      }
    });
  }
  initializeStatusBar() {
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("ai-cos-status");
    this.statusBarItem.setText("AI CoS: Loading...");
    this.registerInterval(
      window.setInterval(() => this.refreshStatusBar(), 6e4)
    );
    setTimeout(() => this.refreshStatusBar(), 2e3);
  }
  async refreshStatusBar() {
    if (!this.statusBarItem)
      return;
    try {
      const ollamaOk = await this.ollamaService.testConnection();
      const googleOk = this.googleAuthService.isAuthenticated();
      const ollamaStatus = ollamaOk ? "\u{1F7E2}" : "\u{1F534}";
      const googleStatus = googleOk ? "\u{1F7E2}" : "\u{1F534}";
      this.statusBarItem.setText(`AI CoS: Ollama ${ollamaStatus} | Google ${googleStatus}`);
      this.statusBarItem.setAttr("title", `Ollama: ${ollamaOk ? "Connected" : "Offline"}
Google: ${googleOk ? "Authenticated" : "Not connected"}`);
    } catch (e) {
      this.statusBarItem.setText("AI CoS: \u26A0\uFE0F");
    }
  }
  async updateStatusBar() {
    await this.refreshStatusBar();
  }
  onunload() {
    var _a, _b;
    (_a = this.meetingPrepFeature) == null ? void 0 : _a.stopAutoCheck();
    (_b = this.inboxTriageFeature) == null ? void 0 : _b.stopAutoTriage();
    console.log("AI Chief of Staff plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  initializeServices() {
    this.ollamaService = new OllamaService(
      this.settings.ollamaUrl,
      this.settings.ollamaModel
    );
    this.googleAuthService = new GoogleAuthService(this);
    this.calendarService = new CalendarService(this.googleAuthService);
    this.gmailService = new GmailService(this.googleAuthService);
    this.smartConnectionsService = new SmartConnectionsService(this.app);
  }
  initializeFeatures() {
    this.meetingPrepFeature = new MeetingPrepFeature(
      this.app,
      this.ollamaService,
      this.calendarService,
      this.smartConnectionsService,
      this.settings.dailyNotePath
    );
    this.inboxTriageFeature = new InboxTriageFeature(
      this.app,
      this.ollamaService,
      this.gmailService,
      this.smartConnectionsService,
      this.settings.inboxNotePath
    );
    this.timeAuditFeature = new TimeAuditFeature(
      this.app,
      this.ollamaService,
      this.calendarService,
      this.settings.weeklyReviewPath
    );
  }
  updateServices() {
    this.ollamaService.updateConfig(
      this.settings.ollamaUrl,
      this.settings.ollamaModel
    );
  }
  updateFeatures() {
    this.meetingPrepFeature.updateConfig(this.settings.dailyNotePath);
    this.inboxTriageFeature.updateConfig(this.settings.inboxNotePath);
    this.timeAuditFeature.updateConfig(this.settings.weeklyReviewPath);
  }
  startBackgroundTasks() {
    if (this.googleAuthService.isAuthenticated()) {
      this.meetingPrepFeature.startAutoCheck(this.settings.meetingPrepMinutesBefore);
    }
  }
  registerCommands() {
    this.addCommand({
      id: "summarize-current-note",
      name: "Summarize Current Note",
      editorCallback: async (editor) => {
        const content = editor.getValue();
        if (!content.trim()) {
          new import_obsidian6.Notice("Note is empty");
          return;
        }
        new import_obsidian6.Notice("Summarizing note...");
        try {
          const summary = await this.ollamaService.summarizeNote(content);
          editor.replaceSelection(`

---

## AI Summary

${summary}

---

`);
          new import_obsidian6.Notice("Summary generated!");
        } catch (error) {
          new import_obsidian6.Notice(`Failed to summarize: ${error}`);
        }
      }
    });
    this.addCommand({
      id: "query-vault",
      name: "Query Vault with AI",
      callback: async () => {
        const query = await this.promptForInput("Enter your query:");
        if (!query)
          return;
        new import_obsidian6.Notice("Searching vault...");
        try {
          const relatedNotes = await this.smartConnectionsService.getRelatedNotes(query, 5);
          const response = await this.ollamaService.queryVaultWithContext(query, relatedNotes);
          await this.createOrAppendNote(
            "AI Query Results.md",
            `## Query: ${query}

${response}

*Generated: ${(/* @__PURE__ */ new Date()).toLocaleString()}*

---

`
          );
          new import_obsidian6.Notice("Query results saved to AI Query Results.md");
        } catch (error) {
          new import_obsidian6.Notice(`Query failed: ${error}`);
        }
      }
    });
    this.addCommand({
      id: "prepare-next-meeting",
      name: "Generate Meeting Note Debrief",
      callback: async () => {
        if (!this.googleAuthService.isAuthenticated()) {
          new import_obsidian6.Notice("Please connect to Google first (Settings > AI Chief of Staff)");
          return;
        }
        new import_obsidian6.Notice("Generating meeting debrief...");
        try {
          await this.meetingPrepFeature.generateBriefManually();
          new import_obsidian6.Notice("Meeting debrief generated!");
        } catch (error) {
          new import_obsidian6.Notice(`Failed to generate debrief: ${error}`);
        }
      }
    });
    this.addCommand({
      id: "triage-inbox",
      name: "Triage Email Inbox",
      callback: async () => {
        if (!this.googleAuthService.isAuthenticated()) {
          new import_obsidian6.Notice("Please connect to Google first (Settings > AI Chief of Staff)");
          return;
        }
        new import_obsidian6.Notice("Triaging inbox...");
        try {
          const emails = await this.inboxTriageFeature.triageInbox();
          new import_obsidian6.Notice(`Triaged ${emails.length} emails. Check ${this.settings.inboxNotePath}`);
        } catch (error) {
          new import_obsidian6.Notice(`Failed to triage inbox: ${error}`);
        }
      }
    });
    this.addCommand({
      id: "weekly-time-audit",
      name: "Generate Weekly Time Audit",
      callback: async () => {
        if (!this.googleAuthService.isAuthenticated()) {
          new import_obsidian6.Notice("Please connect to Google first (Settings > AI Chief of Staff)");
          return;
        }
        new import_obsidian6.Notice("Generating time audit...");
        try {
          await this.timeAuditFeature.generateTimeAudit();
          new import_obsidian6.Notice(`Time audit generated! Check ${this.settings.weeklyReviewPath}`);
        } catch (error) {
          new import_obsidian6.Notice(`Failed to generate audit: ${error}`);
        }
      }
    });
    this.addCommand({
      id: "test-ollama",
      name: "Test Ollama Connection",
      callback: async () => {
        new import_obsidian6.Notice("Testing Ollama connection...");
        const success = await this.ollamaService.testConnection();
        if (success) {
          new import_obsidian6.Notice("\u2705 Ollama is connected and ready!");
        } else {
          new import_obsidian6.Notice("\u274C Cannot connect to Ollama. Check settings.");
        }
      }
    });
    this.addCommand({
      id: "fetch-today-events",
      name: "Fetch Today's Calendar Events",
      callback: async () => {
        if (!this.googleAuthService.isAuthenticated()) {
          new import_obsidian6.Notice("Please connect to Google first");
          return;
        }
        try {
          const events = await this.calendarService.fetchTodayEvents();
          const summary = events.map(
            (e) => `- ${e.summary} (${e.start.toLocaleTimeString()})`
          ).join("\n");
          await this.createOrAppendNote(
            "Today Events.md",
            `# Today's Events

${summary || "No events today"}

*Fetched: ${(/* @__PURE__ */ new Date()).toLocaleString()}*`
          );
          new import_obsidian6.Notice(`Found ${events.length} events`);
        } catch (error) {
          new import_obsidian6.Notice(`Failed to fetch events: ${error}`);
        }
      }
    });
    this.addCommand({
      id: "daily-briefing",
      name: "Start My Day - Daily Briefing",
      callback: async () => {
        if (!this.googleAuthService.isAuthenticated()) {
          new import_obsidian6.Notice("Please connect to Google first (Settings > AI Chief of Staff)");
          return;
        }
        new import_obsidian6.Notice("Generating daily briefing...");
        try {
          await this.generateDailyBriefing();
          new import_obsidian6.Notice("Daily briefing generated!");
        } catch (error) {
          new import_obsidian6.Notice(`Failed to generate briefing: ${error}`);
        }
      }
    });
    this.addCommand({
      id: "install-background-service",
      name: "Install Background Service Daemon",
      callback: () => {
        new import_obsidian6.Notice("Installing background service...");
        try {
          const { exec } = window.require("child_process");
          const path = window.require("path");
          const vaultPath = this.app.vault.adapter.getBasePath();
          const pluginDir = path.join(vaultPath, ".obsidian/plugins/ai-chief-of-staff/backend");
          exec(`node "${path.join(pluginDir, "setup-service.mjs")}" "${vaultPath}"`, (error, stdout, stderr) => {
            if (error) {
              new import_obsidian6.Notice("Failed to install service: " + error.message);
              console.error(stderr);
            } else {
              new import_obsidian6.Notice("\u2705 Background service installed successfully!");
            }
          });
        } catch (e) {
          new import_obsidian6.Notice("Setup error: " + String(e));
        }
      }
    });
  }
  async generateDailyBriefing() {
    if (!this.settings.dailyNotePath) {
      throw new Error("Please configure the Meeting Note Debriefs folder path in settings");
    }
    const today = /* @__PURE__ */ new Date();
    const dateStr = today.toISOString().split("T")[0];
    const events = await this.calendarService.fetchTodayEvents();
    let emails = [];
    let urgentEmails = [];
    try {
      emails = await this.gmailService.fetchUnreadEmails(10);
      urgentEmails = emails.filter((e) => {
        const subject = (e.subject || "").toLowerCase();
        return subject.includes("urgent") || subject.includes("asap") || subject.includes("important");
      });
    } catch (e) {
      console.log("Failed to fetch emails for daily briefing");
    }
    const upcomingEvents = events.filter((e) => e.start && e.start > today).slice(0, 5);
    const formatEventTime = (date) => {
      if (!date)
        return "--:--";
      try {
        return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
      } catch (e) {
        return "--:--";
      }
    };
    const eventsList = upcomingEvents.length > 0 ? upcomingEvents.map((e) => {
      var _a;
      return `| ${formatEventTime(e.start)} | ${e.summary || "Untitled"} | ${((_a = e.attendees) == null ? void 0 : _a.length) || 0} |`;
    }).join("\n") : "| - | No events scheduled | - |";
    const emailSummary = emails.length > 0 ? `You have **${emails.length}** unread emails${urgentEmails.length > 0 ? `, including **${urgentEmails.length}** potentially urgent` : ""}.` : "Your inbox is clear!";
    const urgentSection = urgentEmails.length > 0 ? `
> [!warning] Urgent Emails
${urgentEmails.map((e) => `> - **${e.subject || "No subject"}** from ${(e.from || "Unknown").split("<")[0].trim()}`).join("\n")}
` : "";
    const firstMeetingInfo = upcomingEvents.length > 0 ? `${upcomingEvents[0].summary || "Untitled"} at ${formatEventTime(upcomingEvents[0].start)}` : "None";
    const content = `# \u2600\uFE0F Daily Briefing - ${dateStr}

*Generated at ${today.toLocaleTimeString()}*

## \u{1F4CA} Overview

> [!info] Today at a Glance
> - **${events.length}** calendar events
> - **${emails.length}** unread emails
> - First meeting: ${firstMeetingInfo}

## \u{1F4C5} Today's Schedule

| Time | Event | Attendees |
|------|-------|-----------|
${eventsList}

## \u{1F4E7} Email Status

${emailSummary}
${urgentSection}
## \u2705 Quick Actions

- [ ] Review urgent emails
- [ ] Prepare for first meeting
- [ ] Check weekly priorities

---

*Use the ribbon icons or command palette for Meeting Debriefs, Inbox Triage, or Time Audit*
`;
    let folderPath = this.settings.dailyNotePath;
    if (folderPath.endsWith(".md")) {
      const lastSlash = folderPath.lastIndexOf("/");
      folderPath = lastSlash > 0 ? folderPath.substring(0, lastSlash) : "";
    }
    if (folderPath) {
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (!folder) {
        await this.app.vault.createFolder(folderPath);
      }
    }
    const briefingPath = folderPath ? `${folderPath}/${dateStr}-briefing.md` : `${dateStr}-briefing.md`;
    const existingFile = this.app.vault.getAbstractFileByPath(briefingPath);
    if (existingFile) {
      await this.app.vault.modify(existingFile, content);
    } else {
      await this.app.vault.create(briefingPath, content);
    }
    const leaf = this.app.workspace.getLeaf(false);
    const file = this.app.vault.getAbstractFileByPath(briefingPath);
    if (file) {
      await leaf.openFile(file);
    }
  }
  async promptForInput(message) {
    return new Promise((resolve) => {
      var _a, _b;
      const modal = document.createElement("div");
      modal.style.cssText = `
        position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);
        background: var(--background-primary); padding: 20px; border-radius: 8px;
        box-shadow: 0 4px 20px rgba(0,0,0,0.3); z-index: 9999; min-width: 400px;
      `;
      modal.innerHTML = `
        <div style="margin-bottom: 15px; font-weight: bold;">${message}</div>
        <input type="text" style="width: 100%; padding: 10px; border-radius: 4px; border: 1px solid var(--background-modifier-border);">
        <div style="margin-top: 15px; display: flex; gap: 10px; justify-content: flex-end;">
          <button class="cancel-btn">Cancel</button>
          <button class="submit-btn mod-cta">Submit</button>
        </div>
      `;
      const overlay = document.createElement("div");
      overlay.style.cssText = "position: fixed; inset: 0; background: rgba(0,0,0,0.5); z-index: 9998;";
      document.body.appendChild(overlay);
      document.body.appendChild(modal);
      const input = modal.querySelector("input");
      input.focus();
      const cleanup = () => {
        modal.remove();
        overlay.remove();
      };
      (_a = modal.querySelector(".cancel-btn")) == null ? void 0 : _a.addEventListener("click", () => {
        cleanup();
        resolve(null);
      });
      (_b = modal.querySelector(".submit-btn")) == null ? void 0 : _b.addEventListener("click", () => {
        const value = input.value.trim();
        cleanup();
        resolve(value || null);
      });
      input.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          const value = input.value.trim();
          cleanup();
          resolve(value || null);
        } else if (e.key === "Escape") {
          cleanup();
          resolve(null);
        }
      });
      overlay.addEventListener("click", () => {
        cleanup();
        resolve(null);
      });
    });
  }
  async createOrAppendNote(path, content) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!file) {
      await this.app.vault.create(path, content);
    } else {
      const existingContent = await this.app.vault.read(file);
      await this.app.vault.modify(file, content + "\n\n" + existingContent);
    }
  }
};
