import type { App, TFile } from 'obsidian';
import type { CalendarEvent, TimeCategory } from '../types';
import type { OllamaService } from '../services/ollama';
import type { CalendarService } from '../services/calendar';

export class TimeAuditFeature {
  private app: App;
  private ollama: OllamaService;
  private calendar: CalendarService;
  private weeklyReviewPath: string;

  constructor(
    app: App,
    ollama: OllamaService,
    calendar: CalendarService,
    weeklyReviewPath: string
  ) {
    this.app = app;
    this.ollama = ollama;
    this.calendar = calendar;
    this.weeklyReviewPath = weeklyReviewPath;
  }

  updateConfig(weeklyReviewPath: string): void {
    this.weeklyReviewPath = weeklyReviewPath;
  }

  async generateTimeAudit(): Promise<TimeCategory[]> {
    const events = await this.calendar.fetchWeekEvents();
    
    if (events.length === 0) {
      throw new Error('No calendar events found for the past week');
    }

    const eventsWithDuration = events.map((e, index) => ({
      id: index,
      summary: e.summary,
      duration: (e.end.getTime() - e.start.getTime()) / (1000 * 60 * 60)
    }));

    const totalHours = eventsWithDuration.reduce((sum, e) => sum + e.duration, 0);

    const categorizedData = await this.ollama.categorizeEvents(eventsWithDuration);

    const categories: TimeCategory[] = categorizedData.map(cat => {
      const percentage = totalHours > 0 ? Math.round((cat.totalHours / totalHours) * 100) : 0;
      const eventNames = cat.eventIndices.map(idx => eventsWithDuration[idx]?.summary || 'Unknown');
      return {
        name: cat.category,
        hours: cat.totalHours,
        percentage,
        events: eventNames
      };
    });

    await this.writeWeeklyReview(events, categories, totalHours);

    return categories;
  }

  private async writeWeeklyReview(
    events: CalendarEvent[], 
    categories: TimeCategory[],
    totalHours: number
  ): Promise<void> {
    const now = new Date();
    const weekStart = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const dateRange = `${weekStart.toLocaleDateString()} - ${now.toLocaleDateString()}`;

    const mermaidChart = this.generateMermaidPieChart(categories);
    const categoriesTable = this.generateCategoriesTable(categories);
    const eventsList = this.generateEventsList(events);

    const content = `# 📊 Weekly Time Audit

*Period: ${dateRange}*
*Generated: ${now.toLocaleString()}*

## Time Distribution

\`\`\`mermaid
${mermaidChart}
\`\`\`

## Categories Breakdown

${categoriesTable}

## Summary

- **Total Scheduled Time:** ${totalHours.toFixed(1)} hours
- **Total Events:** ${events.length}
- **Average Event Duration:** ${(totalHours / events.length).toFixed(1)} hours

## All Events This Week

${eventsList}

---

### Insights

Based on your time allocation this week:

${this.generateInsights(categories)}

---

*This report was generated by AI Chief of Staff*
`;

    let file = this.app.vault.getAbstractFileByPath(this.weeklyReviewPath);
    
    if (!file) {
      await this.app.vault.create(this.weeklyReviewPath, content);
    } else {
      await this.app.vault.modify(file as TFile, content);
    }
  }

  private generateMermaidPieChart(categories: TimeCategory[]): string {
    const pieData = categories
      .filter(c => c.percentage > 0)
      .map(c => `    "${c.name}" : ${c.percentage}`)
      .join('\n');

    return `pie showData
    title Time Allocation
${pieData}`;
  }

  private generateCategoriesTable(categories: TimeCategory[]): string {
    const rows = categories.map(c => {
      return `| ${c.name} | ${c.hours.toFixed(1)}h | ${c.percentage}% | ${c.events.length} |`;
    }).join('\n');

    return `| Category | Hours | Percentage | Events |
|----------|-------|------------|--------|
${rows}`;
  }

  private generateEventsList(events: CalendarEvent[]): string {
    const sortedEvents = [...events].sort((a, b) => a.start.getTime() - b.start.getTime());
    
    return sortedEvents.map(e => {
      const date = e.start.toLocaleDateString();
      const time = e.start.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      const duration = ((e.end.getTime() - e.start.getTime()) / (1000 * 60 * 60)).toFixed(1);
      return `- **${e.summary}** - ${date} ${time} (${duration}h)`;
    }).join('\n');
  }

  private generateInsights(categories: TimeCategory[]): string {
    const sorted = [...categories].sort((a, b) => b.percentage - a.percentage);
    const insights: string[] = [];

    if (sorted.length > 0) {
      insights.push(`- Your largest time allocation was **${sorted[0].name}** at ${sorted[0].percentage}% of your scheduled time.`);
    }

    const deepWork = sorted.find(c => c.name.toLowerCase().includes('deep') || c.name.toLowerCase().includes('focus'));
    if (deepWork) {
      if (deepWork.percentage < 20) {
        insights.push(`- Consider blocking more time for deep work. Currently only ${deepWork.percentage}% of your time.`);
      } else {
        insights.push(`- Good focus time allocation with ${deepWork.percentage}% in deep work.`);
      }
    }

    const meetings = sorted.find(c => c.name.toLowerCase().includes('meeting') || c.name.toLowerCase().includes('external'));
    if (meetings && meetings.percentage > 50) {
      insights.push(`- Warning: ${meetings.percentage}% of time in meetings. Consider protecting more maker time.`);
    }

    return insights.length > 0 ? insights.join('\n') : '- No specific insights available. Review your categories manually.';
  }
}
